name: Build LaTeX and Deploy PDF to GitHub Pages

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build PDF
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout repo
        uses: actions/checkout@v4

      - name: 📄 Compile LaTeX (Digital Version)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: 🔄 Rename digital version
        run: mv main.pdf main-digital.pdf

      - name: 📄 Prepare print version config
        run: |
          # Uncomment the inner/outer margin lines for print version
          sed -i 's/% inner=4cm,/inner=4cm,/' conf.tex
          sed -i 's/% outer=2cm,/outer=2cm,/' conf.tex
          # Uncomment openright for print version
          sed -i 's/% openright,/openright,/' conf.tex

      - name: 📄 Compile LaTeX (Print Version)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: 🔄 Rename print version
        run: mv main.pdf main-print.pdf

      - name: 📤 Upload PDFs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pdf-files
          path: |
            main-digital.pdf
            main-print.pdf

      - name: 📂 Prepare deployment folder
        run: |
          mkdir public
          cp main-digital.pdf public/digital.pdf
          cp main-print.pdf public/print.pdf
          cp main-digital.pdf public/index.pdf

          # Commit information to display the version
          COMMIT_SHA=$(git rev-parse --short HEAD)
          COMMIT_DATE=$(git log -1 --format=%cd --date=format:"%d-%m-%Y %H:%M")
          BRANCH_NAME=${GITHUB_REF_NAME}

          cat <<EOF > public/index.html
          <!DOCTYPE html>
          <html lang="es">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Outlier Detection Report</title>
            <!-- Bootstrap CSS -->
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
            <!-- Font Awesome para iconos más bonitos -->
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
            <style>
              :root {
                --bs-body-bg: #111827;
                --bs-body-color: #f3f4f6;
                --bs-primary: #3b82f6;
                --bs-primary-rgb: 59, 130, 246;
              }
              
              body {
                min-height: 100vh;
                display: flex;
                flex-direction: column;
                background-color: var(--bs-body-bg);
                color: var(--bs-body-color);
              }
              
              .navbar {
                background-color: #1f2937;
                box-shadow: 0 2px 10px rgba(0, 0, 0, 0.3);
              }
              
              .pdf-container {
                flex: 1;
                position: relative;
                margin: 0 auto;
                width: 100%;
                background-color: white;
                border-radius: 0.5rem;
                overflow: hidden;
                box-shadow: 0 10px 25px rgba(0, 0, 0, 0.5);
              }
              
              iframe {
                position: absolute;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                border: none;
              }
              
              .btn-primary {
                background-color: var(--bs-primary);
                border-color: var(--bs-primary);
              }
              
              .btn-primary:hover {
                background-color: #2563eb;
                border-color: #2563eb;
              }
              
              .mobile-download {
                display: none;
              }
              
              @media (max-width: 768px) {
                .desktop-download {
                  display: none;
                }
                
                .mobile-download {
                  display: block;
                }
                
                .pdf-container {
                  position: relative;
                  padding-bottom: 150%;
                  height: 0;
                }
              }
            </style>
          </head>
          <body>
            <!-- Bootstrap Navbar -->
            <nav class="navbar navbar-expand-lg navbar-dark mb-4">
              <div class="container">
                <a class="navbar-brand d-flex align-items-center" href="#">
                  <i class="fas fa-file-pdf fs-4 me-2"></i>
                  <span class="fw-bold">Anomaly detection system memo</span>
                </a>
                <div class="desktop-download ms-auto">
                  <a href="digital.pdf" class="btn btn-primary me-2" download>
                    <i class="fas fa-desktop me-2"></i>Digital Version
                  </a>
                  <a href="print.pdf" class="btn btn-outline-primary" download>
                    <i class="fas fa-print me-2"></i>Print Version
                  </a>
                </div>
              </div>
            </nav>

            <!-- Download buttons for mobile -->
            <div class="container mb-4 text-center">
              <div class="mobile-download">
                <a href="digital.pdf" class="btn btn-primary btn-lg me-2" download>
                  <i class="fas fa-desktop me-2"></i>Digital Version
                </a>
                <a href="print.pdf" class="btn btn-outline-primary btn-lg" download>
                  <i class="fas fa-print me-2"></i>Print Version
                </a>
              </div>
            </div>

            <!-- PDF Viewer -->
            <div class="container flex-grow-1 d-flex flex-column mb-4">
              <div class="pdf-container flex-grow-1">
                <iframe src="index.pdf" class="border-0"></iframe>
              </div>
            </div>

            <!-- Footer with additional information -->
            <footer class="py-3 mt-auto text-light" style="background-color: #1f2937;">
              <div class="container text-center">
                <small>© 2025 Outlier Detection - ${COMMIT_DATE} (#${COMMIT_SHA})</small>
              </div>
            </footer>
            
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
          </body>
          </html>
          EOF
      - name: 📤 Upload folder for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
